# Generated by Django 3.0.7 on 2021-06-07 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210521_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='hierarchy',
        ),
        migrations.CreateModel(
            name='Hierarchy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Company')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Hierarchy')),
            ],
        ),
        migrations.AlterField(
            model_name='machine',
            name='hierarchy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Hierarchy'),
        ),
    ]
