# Generated by Django 3.0.7 on 2021-06-13 00:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210609_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vibrouser',
            name='phone',
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(default='', max_length=17, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe ser ingresado en el formato: xxxxxxx.', regex='^\\d{7}$')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='picture',
            field=models.ImageField(default='company/default.png', upload_to='company'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='diagram',
            field=models.ImageField(default='machine/diagrams/deafult.png', upload_to='machine/diagrams'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='image',
            field=models.ImageField(default='machine/images/deafult.png', upload_to='machine/images'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='power',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='machine',
            name='rpm',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measurement',
            name='service',
            field=models.CharField(choices=[('predictivo', 'Predictivo'), ('correctivo', 'Correctivo'), ('ingeniería', 'Ingeniería'), ('monitoreo', 'Monitoreo en Línea')], default='predictivo', max_length=18),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='backend.Machine'),
        ),
        migrations.AlterField(
            model_name='vibrouser',
            name='celphone',
            field=models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(message='El número de celular debe ser ingresado en el formato: xxxxxxxxxx.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='vibrouser',
            name='picture',
            field=models.ImageField(default='user/profile/default.png', upload_to='user/profile'),
        ),
    ]
