# Generated by Django 3.0.7 on 2021-06-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20210612_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='identifier',
            field=models.IntegerField(),
        ),
    ]
