# Generated by Django 3.0.7 on 2021-06-14 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20210612_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='severity',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow'), ('black', 'Black'), ('purple', 'Purple')], default='purple', max_length=9),
        ),
        migrations.AlterField(
            model_name='flaw',
            name='severity',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow'), ('black', 'Black'), ('purple', 'Purple')], default='purple', max_length=6),
        ),
        migrations.AlterField(
            model_name='machine',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='backend.Company'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='severity',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow'), ('black', 'Black'), ('purple', 'Purple')], default='purple', max_length=9),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='arduino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor', to='backend.Machine'),
        ),
    ]
