# Generated by Django 3.0.7 on 2021-06-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20210614_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='analysis',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='diagnostic',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='prev_changes',
            field=models.TextField(default=''),
        ),
    ]
