# Generated by Django 3.0.7 on 2021-06-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20210618_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='alineacion',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow'), ('black', 'Black'), ('purple', 'Purple')], default='green', max_length=9),
        ),
        migrations.AddField(
            model_name='measurement',
            name='balanceo',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow'), ('black', 'Black'), ('purple', 'Purple')], default='green', max_length=9),
        ),
        migrations.AddField(
            model_name='measurement',
            name='bien',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow'), ('black', 'Black'), ('purple', 'Purple')], default='green', max_length=9),
        ),
        migrations.AddField(
            model_name='measurement',
            name='electrico',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow'), ('black', 'Black'), ('purple', 'Purple')], default='green', max_length=9),
        ),
        migrations.AddField(
            model_name='measurement',
            name='estructural',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow'), ('black', 'Black'), ('purple', 'Purple')], default='green', max_length=9),
        ),
        migrations.AddField(
            model_name='measurement',
            name='excentricidad',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow'), ('black', 'Black'), ('purple', 'Purple')], default='green', max_length=9),
        ),
        migrations.AddField(
            model_name='measurement',
            name='fractura',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow'), ('black', 'Black'), ('purple', 'Purple')], default='green', max_length=9),
        ),
        migrations.AddField(
            model_name='measurement',
            name='holgura',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow'), ('black', 'Black'), ('purple', 'Purple')], default='green', max_length=9),
        ),
        migrations.AddField(
            model_name='measurement',
            name='inspeccion',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow'), ('black', 'Black'), ('purple', 'Purple')], default='green', max_length=9),
        ),
        migrations.AddField(
            model_name='measurement',
            name='lubricacion',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow'), ('black', 'Black'), ('purple', 'Purple')], default='green', max_length=9),
        ),
        migrations.AddField(
            model_name='measurement',
            name='no_medido',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow'), ('black', 'Black'), ('purple', 'Purple')], default='green', max_length=9),
        ),
        migrations.AddField(
            model_name='measurement',
            name='otro',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow'), ('black', 'Black'), ('purple', 'Purple')], default='green', max_length=9),
        ),
        migrations.AddField(
            model_name='measurement',
            name='resonancia',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow'), ('black', 'Black'), ('purple', 'Purple')], default='green', max_length=9),
        ),
        migrations.AddField(
            model_name='measurement',
            name='rodamientos',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow'), ('black', 'Black'), ('purple', 'Purple')], default='green', max_length=9),
        ),
        migrations.AddField(
            model_name='measurement',
            name='soltura',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow'), ('black', 'Black'), ('purple', 'Purple')], default='green', max_length=9),
        ),
        migrations.AddField(
            model_name='measurement',
            name='tension',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow'), ('black', 'Black'), ('purple', 'Purple')], default='green', max_length=9),
        ),
        migrations.AddField(
            model_name='measurement',
            name='vacio',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow'), ('black', 'Black'), ('purple', 'Purple')], default='green', max_length=9),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='analysis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='diagnostic',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='prev_changes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
