# Generated by Django 3.0.7 on 2021-06-21 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20210620_2234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flaw',
        ),
    ]
