# Generated by Django 3.0.7 on 2021-06-27 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_delete_flaw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='bien',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='no_medido',
        ),
    ]
