# Generated by Django 3.0.7 on 2021-06-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20210626_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='identifier',
            field=models.IntegerField(unique=True),
        ),
    ]
