# Generated by Django 3.0.7 on 2021-07-04 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20210628_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='severity',
        ),
        migrations.AddField(
            model_name='values',
            name='severity',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow'), ('black', 'Black'), ('purple', 'Purple')], default='purple', max_length=9),
        ),
    ]
