# Generated by Django 3.0.7 on 2021-07-18 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20210703_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='values',
            old_name='tendency',
            new_name='overall',
        ),
        migrations.RenameField(
            model_name='values',
            old_name='espectra',
            new_name='spectra',
        ),
        migrations.AlterField(
            model_name='machine',
            name='identifier',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
