# Generated by Django 3.0.6 on 2020-06-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200603_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='vibrouser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('engineer', 'Engineer'), ('client', 'Client'), ('support', 'Support')], default='client', max_length=8),
        ),
    ]
