# Generated by Django 3.0.7 on 2020-06-07 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_vibrouser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='engineer_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eng_one', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='measurement',
            name='engineer_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eng_two', to=settings.AUTH_USER_MODEL),
        ),
    ]
