# Generated by Django 3.0.7 on 2020-06-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200606_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='machines'),
        ),
        migrations.AlterField(
            model_name='termoimage',
            name='image',
            field=models.ImageField(upload_to='termals'),
        ),
    ]
