# Generated by Django 3.0.7 on 2020-06-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'state')},
        ),
    ]
