from .is_staff_or_superuser import TestIsStaffOrSuperUser
from .is_update_method import TestIsUpdateMethod
from .has_user_permissions import TestHasUserPermissions
from .can_generate_report import TestCanGenerateReport
