const domain = "http://127.0.0.1:8000"
export const LOGIN_WITH_JWT_ENDPOINT = `${domain}/api/auth/login/`
export const UPDATE_USER_PROFILE_ENDPOINT = `${domain}/api/vibrouser/`
export const REGISTER_WITH_JWT_ENDPOINT = `${domain}/api/auth/register`
export const GET_USER_WITH_JWT_ENDPOINT = `${domain}/api/auth/user`
export const REFRESH_JWT_ENDPOINT = `${domain}/api/auth/refresh/`
export const GET_COMPANIES_ENDPOINT = `${domain}/api/company/`
export const GET_USERS_ENDPOINT = `${domain}/api/vibrouser/`
export const POST_COMPANY_ENDPOINT = `${domain}/api/company/`
export const GET_MACHINES_ENDPOINT = `${domain}/api/machine/`